### ISSUE TITLE
Could not find `IcalReader` in `ical`

### ISSUE THREAD

**Issue by Wildhoney** [Peltoche/ical-rs#16]
With:

```toml
[dependencies]
ical = "0.2.0"
```

I get "**Could not find `IcalReader` in `ical`**" error using the example from the README:

```rust
extern crate ical;

use std::io::BufReader;
use std::fs::File;

fn main() {
    let buf = BufReader::new(File::open("/england-and-wales.ics")
        .unwrap());

    let reader = ical::IcalReader::new(buf);

    for line in reader {
        println!("{:?}", line);
    }
}
```

Which newbie mistake am I making?

**Comment by Wildhoney** [comment]
With fresh eyes this morning I see in the source it's actually [`parser::ical::IcalParser`](`https://github.com/Peltoche/ical-rs/blob/master/src/lib.rs#L15). Is this just a simple case of an error in the README?

**Comment by Peltoche** [comment]
Hello @Wildhoney,

Yep there is an error... I have changed many thing recently and I  missed that. The README should say `IcalParser` but I have also forgotten to make an alias.

So you can use directly `parser::ical::IcalParser` for now and I will fix that in the next version.

Thanks for the issue,

**Comment by Wildhoney** [comment]
Thanks @Peltoche 👍
