### ISSUE TITLE
Documentation is missing some things

### ISSUE THREAD

**Issue by matthiasbeyer** [Peltoche/ical-rs#26]
The linked documentation points to 0.3.0, which seems not to be the latest version of this crate.

The [documentation for 0.4.0 over at docs.rs](https://docs.rs/ical/0.4.0/ical/index.html) is missing some things, mainly the `IcalCalendar` type which is yielded by [iterating over the `IcalParser` type](https://docs.rs/ical/0.4.0/ical/parser/ical/struct.IcalParser.html), but maybe also more.

**Comment by Peltoche** [comment]
Hi @matthiasbeyer,

Thanks for the report. I have resolved the issue by changing the documentation link for the doc.rs website.
