### ISSUE TITLE
InvalidComponent for DAYLIGHT and STANDARD components

### ISSUE THREAD

**Issue by meskio** [Peltoche/ical-rs#27]
Some ics files I found in the wild contain `DAYLIGHT` and `STANDARD` subcomponents inside the `VTIMEZONE` component. It seems to be a valid RFC 5545:
https://tools.ietf.org/html/rfc5545#section-3.6.5

Right now ical-rs returns a parsing error `InvalidComponent` if this components are found. I don't need ical-rs to be able to parse them, but will be nice if it was more permissive and be able to parse this files.

**Comment by Peltoche** [comment]
Hi @meskio,

Thanks for the report. I see that @jbg have a solution inside his fork. I merge it into this repo.

#29

**Comment by Peltoche** [comment]
Merge done!

**Comment by meskio** [comment]
Nice, it works with my examples.

Thanks for the fix.
