### ISSUE TITLE
IcalEvent and others are private

### ISSUE THREAD

**Issue by anlumo** [Peltoche/ical-rs#28]
I can't pass single events to other functions, because I can't reference the type `IcalEvent` by name, since it's in the private module “component”.

The same is true for everything else in `ical::parser::ical::component` except `IcalParser`, which is reexported from the top level module.

**Comment by Peltoche** [comment]
Hello @anlumo,

Thanks for the report. Can you be more specific? Do you have an example?

**Comment by anlumo** [comment]
[Here's the code](https://github.com/Metalab/redalert/blob/75fa61e3dca604a24c4300918085924a6a8e6641/src/main.rs#L62). I'd like to move this for-loop into its own function but I can't.

**Comment by Peltoche** [comment]
@anlumo The review above should fix you issue. Could you review it juste to be sure please?

**Comment by anlumo** [comment]
Yes, it works! Thank you!
