### ISSUE TITLE
Parsing from a `String`?

### ISSUE THREAD

**Issue by teymour-aldridge** [Peltoche/ical-rs#40]
I think this a relatively common use-case (e.g. when retrieving data from a remote server), where one has a `String` – is it possible to parse these directly?

**Comment by FliegendeWurst** [comment]
Yes, like this:
```rust
let string = "BEGIN:VCALENDAR\nEND:VCALENDAR".to_owned();
let parsed = ical::IcalParser::new(string.as_bytes());
```

**Comment by teymour-aldridge** [comment]
Cheers! (I *think* I worked that out eventually, but I can't remember now)
