### ISSUE TITLE
Even more highlevel than PropertyParser

### ISSUE THREAD

**Issue by ModProg** [Peltoche/ical-rs#42]
I need a crate to parse ical more high level than just to properties.

I was basically thinking of something like:
```rs
struct VEvent {
start: Option<TimeStamp>,
end: Option<TimeStamp>,
summary: ...
// Unsuported Properties
properties: Vec<Property>,
}
```
Is this something that can be implemented in the scope of this crate, as a PR? Or should I create a high-level crate depending on `ical-rs`?

**Comment by Peltoche** [comment]
Hello @ModProg ,

Sorry for the big delay. This package is in maintenance mode, this means that no further features will be added by me but I gladly accept contributions if you want.

**Comment by ModProg** [comment]
No worries, I'll probably revisit this some time in the future, but my project where I would have used that is currently on hold as well.
