### ISSUE TITLE
Consider adding serde support ?

### ISSUE THREAD

**Issue by daladim** [Peltoche/ical-rs#43]
Thanks for this crate.

I wished it had a `serde` cargo feature, so that I could include e.g. parsed `Property`s into my own structs that `#[derive(Serialize)]`.

I can work around this by writing my own serializer (which is not terribly difficult), but it would be better if it was already included in your crate (I haven't really tried yet, but reading quickly into the serde documentation, it looks like the latter is more difficult than the former, so I'm not even sure I'll be able to do this myself and make a MR for this :-/ )

**Comment by daladim** [comment]
I've done this in #44 , that was actually very simple

**Comment by Peltoche** [comment]
Hello @daladim,

You review have been merged so I close this issue.

Thanks again for the contribution.

**Comment by daladim** [comment]
Thanks @peltoche. When are you considering releasing a new version of ical?

I'd like to publish a crate that depends on yours (including my commit), but I cannot do so in case a dependency of mine is not published either :-(
