### ISSUE TITLE
Panics when fed invalid UTF-8 as input

### ISSUE THREAD

**Issue by 5225225** [Peltoche/ical-rs#45]
To reproduce, feed the parser any invalid UTF-8.

My test was

```rust
fuzz_target!(|data: &[u8]| {
    let c = std::io::Cursor::new(data);
    for _ in ical::IcalParser::new(c) {}
});
```

The iterator is already over Result's to indicate errors, so I would expect invalid UTF-8 to be just an `Err` yielded.

**Comment by Peltoche** [comment]
Hello @5225225 , thanks for the report and sorry for the delay. I don't have much time to spend on this lib but I will take a look.
