### ISSUE TITLE
Release a 0.8 version?

### ISSUE THREAD

**Issue by daladim** [Peltoche/ical-rs#48]
Hi,

(I'm not sure whether you received notifications about my previous messages in closed issues, so I'm creating a new issue, sorry for the duplication).
Now you've merged #44 , could you release a 0.8 version?

That's because I'd like to use `ical` in my own crate, and I cannot publish my own crate with dependencies that are not published in crates.io (and I'd like to avoid publishing a "temporary" fork of your crate that I'll have to deprecate once you publish 0.8...)

Thanks

**Comment by Peltoche** [comment]
Hello @daladim ,

Sorry for the little delay (more than a year!!!! :scream: ). I have published the v0.8.0 so it should be good now. 

I close this issue, feel free to reopen it if needed.
